Repository ramesht007/Its_all_about_machine_learning, pull requests merged in 2020-10, with the labels that each got.

#8 added LSTM
  LSTM/LSTM.ipynb
Labels: enhancement

#6 added Linear Regressor
  LinearRegressor/Linear-Regressor.ipynb
Labels: enhancement

#9 Added neural netowrks
  Neural Networks/NN.ipynb
Labels: enhancement

#11 Add Principal Component Analysis
  PCA/principal_component_analysis.ipynb
Labels: Hacktoberfest, enhancement

#12 Logistic Regression added
  Logistic Regression/Logistic Regression.ipynb
Labels: Hacktoberfest, enhancement, good first issue

#13 Added Data PreProcessing algorithm
  Data_PreProcessing/Data.csv
  Data_PreProcessing/README.md
  Data_PreProcessing/data_preprocessing_img1.jpg
  Data_PreProcessing/data_preprocessing_img2.jpg
  Data_PreProcessing/data_preprocessing_tools.ipynb
Labels: enhancement

#7 Added XGBRegressor
  XGBRegressor/XGBRegressor.ipynb
Labels: enhancement, hacktoberfest-accepted

#17 Patch 1
  README.md
Labels: hacktoberfest-accepted

#18 Improved_docs
  README.md
Labels: hacktoberfest-accepted

#19 improved
  README.md
Labels: hacktoberfest-accepted

#20 Docs
  README.md
Labels: hacktoberfest-accepted
